# Generated by Django 3.2 on 2021-04-22 02:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superheroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('superpower', models.CharField(choices=[('Volar', 'Volar'), ('Superinteligencia', 'Superinteligencia'), ('Vista de rayo láser', 'Vista de rayo láser'), ('Billetera gorda', 'Billetera gorda')], max_length=19)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
