# Generated by Django 3.2 on 2021-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroe',
            name='date',
            field=models.DateField(),
        ),
    ]
