# Generated by Django 3.2 on 2021-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_superheroe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroe',
            name='heroe_villano',
            field=models.CharField(choices=[('Heroe', 'Heroe/Heroina'), ('Villano', 'Villano/Villana')], default='Heroe', max_length=15),
            preserve_default=False,
        ),
    ]
