# Generated by Django 3.2 on 2021-04-24 14:50

from django.db import migrations
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210424_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superheroe',
            name='header_image',
            field=s3upload.fields.S3UploadField(default=2, dest='example_destination'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superheroe',
            name='profile_image',
            field=s3upload.fields.S3UploadField(dest='example_destination'),
        ),
    ]
